### ISSUE TITLE
Sprockets can't find template file

### ISSUE THREAD

**Issue by recipher** [jimmycuadra/jquery-tmpl-rails#2]
Sprockets raises an error trying to require the file

application.js:1Uncaught Error: Sprockets::FileNotFound: couldn't find file 'tmpl/message'
  (in /Users/recipher/code/mentor/app/assets/javascripts/application.js:30)

It raises the same error if the file is in the tmpl directory or in the root of javascripts.

If I put a leading / into the require:

/tmpl/message

The error does not get raised but when calling $.tmpl("tmpl/message", ...) the template is not used and the template filename is written out.

**Comment by jimmycuadra** [comment]
Based on my investigation, it seems Sprockets will not raise `Sprockets::FileNotFound` if you require an absolute path, even if the file doesn't exist. This seems like a bug, but I will look into that separately.

If you run `$.tmpl("tmpl/message", ...)` when no template has been compiled with the name "tmpl/message", jQuery.tmpl does indeed return the contents of that string as the rendered template. This would be the case when you use an absolute path to require your tmpl file, as Sprockets will not choke, but your rendered asset file will not have the template in it.

This means the real question is why a simple `//= require tmpl/message` does not find your tmpl file. Can you provide the contents of your manifest file, the tmpl file, and the relevant directory structure with file names?

**Comment by recipher** [comment]
Hi. I've swapped it back now but this is the structure:

https://github.com/recipher/mentor/tree/master/app/assets/javascripts

The templates are in here:

https://github.com/recipher/mentor/tree/master/app/assets/javascripts/tmpl

I was just renaming them, .tmpl and adding

//= require tmpl/message 

to application.js

Thanks.

**Comment by jimmycuadra** [comment]
I see three issues:
1. You have the old version of the gem in your Gemfile.lock. Try running `bundle update jquery-tmpl-rails` to get the new one with the Sprockets engine.
2. The new version requires you to require `jquery-tmpl` instead of `jquery.tmpl` in your manifest file.
3. The template file extensions should have an extension of `.tmpl` instead of `.html`.

I believe those three changes will solve your issue.

**Comment by recipher** [comment]
Grand. The templates are named .html at the moment because I've gone back to my other solution (on-demand loading from the browser).

I'll give that a whirl when I get a chance.

**Comment by jimmycuadra** [comment]
Cool. Closing the issue for now but feel free to reopen it if the above points don't solve it for you.
