### ISSUE TITLE
Vendor asset no more included

### ISSUE THREAD

**Issue by levraipixel** [jimmycuadra/jquery-tmpl-rails#6]
Hi,

Since you removed inheritance from Rails::Engine, Rails doesn't known you're providing the asset "jquery-tmpl", and your gem doesn't appear in Rails.application.config.assets.paths anymore.
Could you fix this, please ?

**Comment by jimmycuadra** [comment]
Major fail on my part. So sorry. 1.0.1 is out now with the fix.
